env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  # https://github.com/babel/eslint-plugin-babel
  - babel

extends:
  - standard
  - 'plugin:jest/recommended'

rules: {}
